# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: 
url: https://thalesh.github.io
date_format: "ordinal"
title: Curiosity
author: Thales

# ---------------- #
#   RSS / Email    #
# ---------------- #
subscribe_rss: /feed.xml
email:

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: redcarpet 
highlighter: pygments
paginate: 9
permalink: /:year/:month/:day/:title/

gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jekyll/scholar

redcarpet: 
    extentions:["no_intra_emphasis","fenced_code_blocks","autolink","tables","strikethrough","with_toc_data"]

collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
#duoshuo_short_name: Thales
changyan: false
